import { StyleSheet, Platform } from 'react-native';
import { colors } from './src/styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.cardBackground, 
  },
  map: {
    flex: 1,
    width: '100%',
    // O flex: 1 dentro de um SafeAreaView com edge 'bottom' 
    // fará o mapa respeitar a barra de navegação no Android.
  },
  
  destinationBadge: {
    position: 'absolute', 
    bottom: Platform.OS === 'android' ? 60 : 50, 
    alignSelf: 'center', 
    backgroundColor: 'white', 
    paddingHorizontal: 20, 
    paddingVertical: 10, 
    borderRadius: 25, 
    elevation: 5,
    borderWidth: 1,
    borderColor: colors.cardBackground,
    zIndex: 10 
  },
  destinationText: {
    color: colors.cardBackground, 
    fontWeight: 'bold',
    fontSize: 14,
  },

  // Estilos de Marcadores
  poiMarker: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#0077b6',
    borderWidth: 2,
    borderColor: 'white',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1,
  },

  alertContainer: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  alertBox: {
    width: '85%',
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 25,
    alignItems: 'center',
    elevation: 10,
  },
  alertTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.cardBackground,
  },
  alertMessage: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
    lineHeight: 22,
  },
  alertButton: {
    backgroundColor: colors.cardBackground,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
  },
  alertButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  recenterButton: {
  position: 'absolute',
  right: 20,
  bottom: Platform.OS === 'android' ? 120 : 120, 
  backgroundColor: 'white',
  width: 50,
  height: 50,
  borderRadius: 25,
  justifyContent: 'center',
  alignItems: 'center',
  elevation: 5,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.25,
  shadowRadius: 3.84,
  zIndex: 10,
  },
  destinationBadge: {
  position: 'absolute', 
  bottom: 60, 
  alignSelf: 'center', 
  backgroundColor: 'white', 
  paddingHorizontal: 15, // Respiro lateral
  paddingVertical: 10, 
  borderRadius: 25, 
  elevation: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 4.65,
  borderWidth: 1,
  borderColor: colors.cardBackground,
  zIndex: 10,
  },
  skipButton: {
    position: 'absolute',
    top: 190, 
    right: 20, 
    backgroundColor: '#1C2B40', 
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20, 
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  skipButtonText: {
    color: '#FFF',
    fontWeight: '500', 
    marginLeft: 6,
    fontSize: 14, 
  },
});