import { StyleSheet, Platform } from 'react-native';
// Caminho corrigido: subindo dois andares para achar a pasta styles geral
import { colors } from '../../styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.cardBackground, 
  },
  map: {
    flex: 1,
    width: '100%',
  },
  
  destinationBadge: {
    position: 'absolute',
    bottom: 60, 
    left: 15,
    right: 15, 
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row', 
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
  },
  badgeIconContainer: {
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeTextContainer: {
    flex: 1, 
    justifyContent: 'center',
  },
  destinationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#333',
    marginBottom: 4, 
    lineHeight: 20,
  },
  destinationDistance: {
    fontSize: 13,
    color: '#666',
  },
  destinationText: {
    color: colors.cardBackground, 
    fontWeight: 'bold',
    fontSize: 14,
  },

  poiMarker: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#0077b6',
    borderWidth: 2,
    borderColor: 'white',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1,
  },

  alertContainer: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  alertBox: {
    width: '85%',
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 25,
    alignItems: 'center',
    elevation: 10,
  },
  alertTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.cardBackground,
  },
  alertMessage: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
    lineHeight: 22,
  },
  alertButton: {
    backgroundColor: colors.cardBackground,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
  },
  alertButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  recenterButton: {
    position: 'absolute',
    right: 15,
    bottom: Platform.OS === 'android' ? 175 : 175, 
    backgroundColor: 'white',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 10,
  },
  badgeFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between', 
    alignItems: 'center',
    marginTop: 4, 
  },
  inlineSkipButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8EBF0', 
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  inlineSkipText: {
    color: colors.cardBackground, 
    fontWeight: '700',
    fontSize: 13,
    marginRight: 4,
  },
});